### ISSUE TITLE
Corrupted Video Stream

### ISSUE THREAD

**Issue by aPere3** [afg984/pyardrone#11]
I try to stream images from the two cameras on the drone using the following piece of code:

drone = ARDrone()
drone.send(at.CONFIG('video:video_channel', 1))  #select the bottom cam
drone.send(at.CONFIG('video:video_codec', 128)) #tries to change video codec, but it doesn't seem to work, anyway having this line or not doesn't change enything
drone.video_ready.wait()
try:
    while True:
        cv2.imshow('im', drone.frame)
        if cv2.waitKey(10) == ord(' '):
            break
finally:
    drone.close()

I get a scattered image, like those ones:

![capture du 2016-02-10 12 54 18](https://cloud.githubusercontent.com/assets/13695792/12946536/8abf0d9c-cff5-11e5-8c8c-bd1049227397.png)
![capture du 2016-02-10 12 54 25](https://cloud.githubusercontent.com/assets/13695792/12946537/8ad316a2-cff5-11e5-9481-2c2937f978dd.png)

In the console I obtain the following messages:

[h264 @ 0x7f651c0034c0] error while decoding MB 24 12
[h264 @ 0x7f651c75d680] dquant out of range (2565) at 15 14
[h264 @ 0x7f651c75d680] error while decoding MB 15 14
[h264 @ 0x7f651c0029a0] cbp too large (4294967295) at 32 14
[h264 @ 0x7f651c0029a0] error while decoding MB 32 14
[h264 @ 0x7f651c002f40] dquant out of range (-404) at 6 2
[h264 @ 0x7f651c002f40] error while decoding MB 6 2

which makes me think that MP4 is not set... 

I use anaconda3 and OpenCV3 on a linux machine. Is there any link between opencv and ffmpeg in your implementation? Because, i'm not that shure of my ffmpeg install...

**Comment by afg984** [comment]
> ``drone.video_ready.wait()``

this line is meant to ensure that the the ARDrone object has received at least one video frame

> which makes me think that MP4 is not set...

you're right, I didn't figure out how to do it.

> Is there any link between opencv and ffmpeg in your implementation?

my implementation does not use ffmpeg directly, opencv uses ffmpeg internally (or gstreamer, etc) for video decoding

https://github.com/Itseez/opencv/tree/master/3rdparty/ffmpeg states so:
> On Linux and other Unix flavors OpenCV uses default or user-built ffmpeg/libav libraries.

The implementation reads the video from ``video_port``, then remove the ``PaVE`` header, then send the remaining stuff to some free udp port.
Then it uses opencv to read from the udp port.

for example: port 3333
``cv2.VideoCapture('udp://localhost:3333')`` (video.py, Line112)

I read somewhere that the functionality of reading from a UDP stream is provided by opencv's ffmpeg backend. So any URI supported by ffmpeg will be available to OpenCV, and I'm taking that advantage.

however, it seems impossible to set mp4 in the url itself (https://www.ffmpeg.org/ffmpeg-protocols.html#udp), 
and I couldn't find an obvious way to do it with VideoCapture (http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-videocapture)
maybe we can add a header or something?

Please keep in mind that the implementation is more like a workaround than a good solution, as I'm pretty unfamiliar to video codecs.

Any suggestions?

**Comment by aPere3** [comment]
Okay, I managed to obtain good frames, on a fresh install of opencv using the last ffmpeg(2.9) directly loaded and compiled from the [git repository](https://github.com/FFmpeg/FFmpeg). Previously I was using the archive from the website which was  only the 2.8 version. 

Don't understand why ffmpeg is not directely supported by ubuntu anyway...

Thank you for advises.
