### ISSUE TITLE
Nav datareadout issue

### ISSUE THREAD

**Issue by tretron** [afg984/pyardrone#12]
trying to operate the drone via the lib I try to read the sensors via
drone.send(at.CONFIG('general:navdata_demo', True)) 
with the the following command
drone.navdata.demo.vbat_flying_percentage

The error message i get is  "demo" is not an atrubute of navdata

What is the issue with this program? i know demo is not activated untill the drone sends sensor data back 

program:
`from pyardrone import ARDrone, at
drone=ARDrone()
drone.send(at.CONFIG('general:navdata_demo', True))
drone.navdata_ready.wait()
bat=drone.navdata.demo.vbat_flying_percentage
print(bat)`

**Comment by afg984** [comment]
maybe first wait and then config?
```python
drone.navdata_ready.wait()
drone.send(at.CONFIG('general:navdata_demo', True))
```
sending `at.CONFIG` simply tells the library to send a UDP packet to the drone. The configuration may not be effective in time or the drone might simply drop the configuration.

you might also want to try sending the config multiple times or wait for a while (like `time.sleep`)

btw I no longer own the device so I cannot test

**Comment by tretron** [comment]
Issue is solft, It is a comminucation error between the computer and the drone.
I fixed it with the following code:
```
drone.navdata_ready.wait()
if  drone.navdata_ready.is_set() !=true:
    drone.send(at.CONFIG('general:navdata_demo', True))
```
