### ISSUE TITLE
Read out camera

### ISSUE THREAD

**Issue by tretron** [afg984/pyardrone#13]
with the navigation solft a new issue arries. The issue of read out the camera. I do not know where the problem lays but when implementing drone=ARDrone() before my CV code the cod keeps at the CV2 code. IF i initilaze after it, I get the video but no controll over the drone.

```
drone =ARDrone()
drone.navdata_ready.wait()
drone.send(at.CONFIG('general:navdata_demo'), True)) #intitialize sensors
drone.send(at.CONFIG('video:video_channel', 2)) #sellect down facing camera
drone.navdata_ready.wait() #make sure the drone is ready.
webcam = cv2('tcp://192.168.1.1:5555') #read out cammera
```

It might be a conflic between the two libraries of open CV2 and pyardrone. However I realise the Pyardrone library has a build in function to add a video stream the ''pyardrone.video.VideoMixin'' class. But how precisely does that class work? `drone.video.VideoMixin`` Give me an error "no attrabute video" I believe I am thinking in the wrong way of how to work with the stream, could you help me out with this?

**Comment by afg984** [comment]
If you have opencv, then video is enabled by default.
Use `drone.video_ready.wait()` to ensure that video is available and use `drone.frame` to acquire the latest video frame

**Comment by tretron** [comment]
The program halts at the ``drone.video_read.wait()``
I double checked my openCV version to be sure that is not the issue. 

```from pyardrone import ARDrone, at
import cv2

dragon = ARDrone()
dragon.navdata_ready.wait()  # wait for first navdata
print(dragon.navdata)
dragon.send(at.CONFIG('general:navdata_demo', True))
dragon.send(at.CONFIG('video:video_channel', 2))
dragon.video_ready.wait()
print('av data ready')

while True:
    image = dragon.frame
    cv2.imshow('beeld1', image)
```

**Comment by afg984** [comment]
Try disabling video support manually:

```python
from pyardrone import ARDroneBase, HelperMixin

class MyARDrone(HelperMixin, ARDroneBase):
    pass

drone = MyARDrone()
```

and see if your manual cv2 works
