### ISSUE TITLE
Class REF(ATCommand) - emergency mode

### ISSUE THREAD

**Issue by mncmilan** [afg984/pyardrone#14]
Hi afg984!

First of all thanks for your contribution, it's pretty awesome!

I’ve been working with pyardrone to test a new control flight system that I’ve created for my bachelor’s thesis (you can check my project here https://github.com/mncmilan/CUBA and here http://steelhummingbird.blogspot.com.es/, note that git repository is not complete yet).

Due to my project, I needed to add some new methods in your API, everything was ok except for the flag that enables/disables the emergency mode in the AR.Drone 2.0, by taking into account the documentation, I guess it should be like this:

```
class REF(ATCommand):

    '''
    Controls the basic behaviour of the drone (take-off/landing, emergency
    stop/reset)
    '''

    input = parameters.Int32(
        'an integer value, '
        'representing a 32 bit-wide bit-field controlling the drone')

    input._set_flags(
        default=bits(18, 20, 22, 24, 28),  # Always on
        start=bits(9),  # Takeoff / Land
        select=bits(18, 20, 22, 24, 28, 8),  # Switch of emergency mode
    )
```

Waiting for your answer ;)

Mónica

**Comment by afg984** [comment]
> 
> Send this command to control the basic behaviour of the drone. With SDK version 1.5, only
> bits 8 and 9 are used in the control bit-field. Bits 18, 20, 22, 24 and 28 should be set to 1. Other
> bits should be set to 0. 
> (SDK2.0 devguide page 22)

From my understanding, bits 18, 20, 22, 24, 28 should always be 1.

Does the documentation say anything about "select" using multiple bits? Please let me know.

**Comment by mncmilan** [comment]
> The following commands sent in a standalone UDP packet will send an emergency signal :
>AT * REF=1,290717696 < CR > AT * REF=2,290717952 < CR > AT * REF=3,290717696 < CR >
> (Page 36 commands description -> AT * REF of SDK2.0 attached)

I found this in the documentation, I'm quite unexperienced so maybe I misunderstood something... However I tried to set the emergency mode with your code, by doing :

`self.send(at.REF(at.REF.input.default | at.REF.input.select | at.REF.input.default))`

And the AR.Drone 2.0 did nothing at all... Whereas with the modifification that I told you in my first message it works. What am I doing wrong?

[ARDrone_Developer_Guide.pdf](https://github.com/afg984/pyardrone/files/769540/ARDrone_Developer_Guide.pdf)

**Comment by afg984** [comment]
OK, now I understand your problem, your're using the low level API directly.

I'll make at.REF always include the default bits.

Besides adding the default bits, would adding a ``drone.emergency()`` method make sense for you?

**Comment by mncmilan** [comment]
Yeah this method would be really useful.
Thanks a lot! ;)
