### ISSUE TITLE
Reading sensor data

### ISSUE THREAD

**Issue by cas2406** [afg984/pyardrone#17]
Hi,

I'm currently running on python 3.5.2 and pyardrone 0.6.1

I am trying to read the demo data using the command "drone.navdata.demo", however i get an error message that demo doesn't exist.
I can call "drone.navdata.metadata" which gives the header, checksum, state, etc.

I have tried to edit the __init__.py file in the navdata folder, because i think the __init__ function is unable to reach the demo data.

should this import line:
from pyardrone.navdata.options import Metadata, OptionHeader, index
be changed to something like
from pyardrone.navdata.options import Metadata, OptionHeader, index, Demo, RawMeasures,PressureRaw

also when looking in the init function itself it looks like it only adds the option for the metadata:
self.add_option(Metadata, buffer, 0)
offset = sizeof(Metadata)

shouldn't all functions be added with the add_option function?

*edit
I did send the AT command to enable demo data

Do you have any idea, how i could get the sensor data?

Kind regards,
Casper

**Comment by afg984** [comment]
No. The `Demo`, `RawMeasures`, `PressureRaw` classes are available from the ``index`` object.

[NavData gets them when decoding](https://github.com/afg984/pyardrone/blob/master/pyardrone/navdata/__init__.py#L65``) as ``option_class``

You might encounter the issue because your ARDrone not sending the demo "option"

**Comment by cas2406** [comment]
I understand, however when i check the navdata_demo_mask it returns True.
So the ARDrone should be sending the demo data if i am correct?

**Comment by afg984** [comment]
There might be other reasons causing ARDrone not sending the demo data.
Maybe[ `navdata_bootstrap`](http://pyardrone.readthedocs.io/en/latest/options/?highlight=navdata_demo_mask#pyardrone.navdata.states.DroneState.navdata_bootstrap)? Or you can always reboot your drone and hope it works next time.
As I do not own the hardware anymore, you'll have to find it out yourself or seek others' help.

**Comment by cas2406** [comment]
I have found the problem, in order to read the demo data send by the parrot.
You also need to import at, so:
from pyardrone import ARDrone, at

after that import you can use:
drone.navdata.demo

**Comment by afg984** [comment]
Importing at does not cause any side effects.

It may just being your device functioning improperly
