### ISSUE TITLE
Windows 10 cannot get frame from drone

### ISSUE THREAD

**Issue by bepo00** [afg984/pyardrone#20]
I am using win 10 (64) python 3 and opencv from conda-forge channel. 
Code:

`from pyardrone import ARDrone

drone = ARDrone()
drone.navdata_ready.wait()
drone.video_ready.wait()
image = drone.frame
`

navdata_ready.wait() -> returns immediatelly with result: true, video_ready.wait() stucks and then I get following result:
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:834)
warning: udp://localhost:59693 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:835)
True

So it still returns True after warnings but drone.video_client.frame is always NONE
FFMPEG is included in opencv. 
Result from cv2.getBuildInformation(): 
Video I/O:
    Video for Windows:           YES
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (ver 57.107.100)
      avformat:                  YES (ver 57.83.100)
      avutil:                    YES (ver 55.78.100)
      swscale:                   YES (ver 4.8.100)
      avresample:                YES (ver 3.7.0)
    DirectShow:                  YES

Tried on lubuntu and it works normally. 
What could I do to make it work on windows?

**Comment by afg984** [comment]
Seems like opencv cannot read video from the socket in Windows. Do you have an active firewall?

**Comment by bepo00** [comment]
I have tried with disabled firewall but the issue still persist. Currently working on linux now so I am closing issue.
