### ISSUE TITLE
A question on navdata

### ISSUE THREAD

**Issue by GigaFlower** [afg984/pyardrone#8]
Hello,I'm using your pyardrone to attend a UAV competition in my school.I want to say it is really a nice one.And I feel lucky that I could find this repository.
Sorry to bother you here,but I can not find a way to contact you privately.If my action makes you feel unpleasant,just tell me directly.
So,my question is I failed to make use of navdata,and the doc says
>>> nav.demo
Demo(.....)

which I feel difficult to understand.
Could you give me some hint?Any will help.
Thank you very much.

**Comment by afg984** [comment]
I think it didn't work because I have disabled the config part of the library (because it's not working properly), but NavData demo requires it to work.
Also I admit that it isn't very clear in the documentation.

I will update both the library and documentation when I get access to the AR Drone hardware tomorrow.

BTW, I maintain this library as a subproject of my UAV project, which is work in progress, so always feel free to ask any question you have encountered.

Thanks for reporting!

**Comment by afg984** [comment]
First of all, I have to apologize that I accidentally removed `ARDrone.navdata`, so please update to 0.5.1 before proceeding.

```python
>>> from pyardrone import ARDrone, at
>>> drone = ARDrone()
>>> drone.navdata_ready.wait()  # wait for first navdata
>>> drone.navdata
NavData(checksum=928, cks=Cks(value=928), metadata=Metadata(header=1432778632, state=1333790928, sequence_number=79367, vision_flag=1))
>>> drone.navdata.metadata
Metadata(header=1432778632, state=1333790928, sequence_number=79367, vision_flag=1)
```

According to the Developer Guide from parrot:
(https://github.com/afg984/pyardrone/raw/dev-resources/ARDrone_Developer_Guide.pdf)
To get navdata_demo you have to send an AT*CONFIG command,
which is
```python
>>> drone.send(at.CONFIG('general:navdata_demo', True))
```
in pyardrone.

And ``drone.navdata.demo`` will be available then.

A higher level API for configuring ARDrone will be available in future versions, though.

**Comment by afg984** [comment]
this is how navdata.demo would look like:
```
>>> drone.navdata.demo
Demo(ctrl_state=131072, vbat_flying_percentage=80, theta=-1700.0, phi=-511.0, psi=5451.0, altitude=0, vx=0.0, vy=0.0, vz=0.0, num_frames=0, detection_camera_rot=[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]], detection_camera_trans=[ 0.  0.  0.], detection_tag_index=0, detection_camera_type=3, drone_camera_rot=[[ 0.99503797 -0.09474134 -0.03038955]
 [ 0.0949671   0.99546188  0.00607054]
 [ 0.0296765  -0.00892643  0.99951971]], drone_camera_trans=[   0.    0. -242.])
```

**Comment by GigaFlower** [comment]
WOW.
It is really nice of you for your helpful response.
I will try them as soon as possible.
And if I encounter any problem which I can't solve myself,I'll go back here for help again :P
Lots of thanks!

**Comment by GigaFlower** [comment]
I test it today and the navdata works well.
It shows context just as you described.
Thanks!

**Comment by GigaFlower** [comment]
Hello!
Today our team passed the semi-final smoothly.
It seems that our team outperformed most of other teams,
which is impossible without your help!

But,I still have some question to bother you,
First,can I access video stream?
Second,can I access data which is not included in demo like battery status?

**Comment by afg984** [comment]
Do you want to access the latest video frame or the entire video stream?

For the latest frame use [drone.frame](http://pyardrone.readthedocs.org/en/latest/ardrone/#video-support)
you must have opencv installed for that to work.

It is quite tricky to get the entire video stream, please tell me if it is an requirement.

For the battery status, I have not used it myself and the only two I found relevant are: 
1. [Demo.vbat_flying_percentage](http://pyardrone.readthedocs.org/en/latest/navdata/#pyardrone.navdata.options.Demo.vbat_flying_percentage)
2. [RawMeasures.vbat_raw](http://pyardrone.readthedocs.org/en/latest/navdata/#pyardrone.navdata.options.RawMeasures.vbat_raw) (accessed via `drone.navdata.raw_measures`, and you have to enable it first. I forgot how to do it, so please refer to the developer guide. I think sending AT Commands is enough.)

The attribute description there is just copied from ARDrone's developer guide, so I have no idea what they could possibly mean. I suggest you try it yourself.

**Comment by GigaFlower** [comment]
Well,I get it.I'll try it later.
And if I make anything work,
I'll not forget to give you a report if you don't mind.

**Comment by afg984** [comment]
@GigaFlower if it is still relevant, please try sending:

```
drone.send(at.CONFIG('general:navdata_options', 5))
```

and see if you can get
```
drone.navdata.raw_measures
```

see also #9 
I currently do not have the device, so please report back if you have the time to test and whether it works or not so I can make enabling navdata much more easier. Thanks.

**Comment by GigaFlower** [comment]
Oh my god,I'm sorry I noticed your reply so late!
Since here goes winter vacation now,I can not access the device either T_T.
May be I can not test it for you until some end of February. ╯︿╰

**Comment by GigaFlower** [comment]
It must be a little late to say it.

But today I finally got the device and tested the 'raw_measures'.

And the result is it did work.

**Comment by GigaFlower** [comment]
Hello,I get stuck (again) ....This time is on video.

Here is the situation:

As soon as I connect to the drone,I get an error in console

`WARNING: Couldn't read movie file udp://localhost:55959`

Then,though `drone.video_ready.wait()` always return a True,`drone.frame` remains none.

I read the guide book and found that 'video stream is sent on port 5555(TCP for AR.Drone 2.0)',

so I tried cv2.VideoCapture('tcp://localhost:5555'), which returned a similar warning as the one I got at first.

Do you have any suggestion on what's going on?

**Comment by GigaFlower** [comment]
BTW,I can receive video with my phone.

**Comment by GigaFlower** [comment]
Now the contest finally ends.We has get a good prize.

Thank you very much for helping me so much. :)
