### ISSUE TITLE
Get magnetometer data from pyardrone.navdata.options.Magneto

### ISSUE THREAD

**Issue by Jackovic** [afg984/pyardrone#9]
Hello,

Very nice module, thanx a lot !
Please, can you provide me a simple example of how to get magnetometer navdata.
I try with :

> > > from pyardrone import ARDrone
> > > drone = ARDrone(host='192.168.1.101')
> > > drone.navdata_ready.wait()
> > > True
> > > drone.navdata.options.Magneto
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: 'NavData' object has no attribute 'options'

Of course, NavData has no method called 'options'
How can i proceed to get this magnetometer value ?
Best!

**Comment by afg984** [comment]
There is currently no easy way to do it, to make it available, try:
```
drone.send(at.CONFIG('general:navdata_options', 4194305))
```

and then hopefully, it can be accessed by:
```
drone.navdata.magneto
```

I don't have the device now. Please tell me if it works or not so I can provide a better way to do it. Thanks.
ref: dev guide p82

**Comment by aPere3** [comment]
Hello, 

I try to send `at.CONFIG` commands to configure the acquired navdata, but I  never get extra methods ( `demo`, `magneto`, `raw_measures`, ...) added to my `drone.navdata`. Does that seem a familiar issue for you?

Thanks

**Comment by afg984** [comment]
@aPere3

I have experience that the drone sometimes ignore `at. CONFIG`

**Comment by aPere3** [comment]
Okay, 

But I don't get how the options structure are added to navdata when a `at.config` commands are sent. I don't know a lot of python so I would be glad that you explain, if you have time... Is there something I can do with the `navdata.addOptions` method? How do I know buffer and offset?

Thanks for all explanations...

**Comment by afg984** [comment]
When you use at.CONFIG to add more navdata options you are actually requesting your physical drone to send more information back to your computer

The various attributes in `drone.navdata` are constructed according to what the drone has sent

So if the physical drone does not send magneto data to your computer, `drone.navdata.magneto` wouldn't be available

For the buffer and offset, let me take another look

**Comment by afg984** [comment]
![image](https://cloud.githubusercontent.com/assets/4318379/13113608/bb059e3c-d5ca-11e5-9a60-29cc540d9c73.png)
The structure of navdata is located on parrot's developer guide page 39
